package wg

import (
	"bytes"
	"fmt"
	"text/template"
)

// ServerConfigParams holds the parameters needed to generate a wg-quick
// server-side config file for export.
type ServerConfigParams struct {
	InterfaceName string
	PrivateKey    string
	Address       string // server IP with CIDR, e.g. "10.0.0.1/24"
	ListenPort    int
	DNSServers    string
	NATEnabled    bool
	NATInterface  string // e.g. "eth0"
	Peers         []ExportPeer
}

// ExportPeer represents a peer in an exported config.
type ExportPeer struct {
	Name                string
	PublicKey           string
	PresharedKey        string
	AllowedIPs          string
	Endpoint            string
	PersistentKeepalive int
}

var serverConfigTmpl = template.Must(template.New("server_config").Parse(
	`# Generated by wgpilot — {{ .InterfaceName }}
[Interface]
PrivateKey = {{ .PrivateKey }}
Address = {{ .Address }}
ListenPort = {{ .ListenPort }}
{{- if .DNSServers }}
DNS = {{ .DNSServers }}
{{- end }}
{{- if .NATEnabled }}
PostUp = iptables -t nat -A POSTROUTING -o {{ .NATInterface }} -j MASQUERADE; ip6tables -t nat -A POSTROUTING -o {{ .NATInterface }} -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -o {{ .NATInterface }} -j MASQUERADE; ip6tables -t nat -D POSTROUTING -o {{ .NATInterface }} -j MASQUERADE
{{- end }}
{{ range .Peers }}
# {{ .Name }}
[Peer]
PublicKey = {{ .PublicKey }}
{{- if .PresharedKey }}
PresharedKey = {{ .PresharedKey }}
{{- end }}
AllowedIPs = {{ .AllowedIPs }}
{{- if .Endpoint }}
Endpoint = {{ .Endpoint }}
{{- end }}
{{- if gt .PersistentKeepalive 0 }}
PersistentKeepalive = {{ .PersistentKeepalive }}
{{- end }}
{{ end }}`))

// GenerateServerConfig produces a wg-quick compatible server config file.
func GenerateServerConfig(params ServerConfigParams) (string, error) {
	if params.PrivateKey == "" {
		return "", fmt.Errorf("generate server config: private key is required")
	}
	if params.ListenPort == 0 {
		return "", fmt.Errorf("generate server config: listen port is required")
	}
	if params.NATEnabled && params.NATInterface == "" {
		params.NATInterface = "eth0"
	}

	var buf bytes.Buffer
	if err := serverConfigTmpl.Execute(&buf, params); err != nil {
		return "", fmt.Errorf("generate server config: %w", err)
	}
	return buf.String(), nil
}
